### PR TITLE
WIP: revive macOS CI

### PR DESCRIPTION
**Pull request by AndreasAlbert**

### CODE REVIEW

**Comment by clelange** [comment]
Currently, we get Python 3.9.5 with homebrew/ROOT as default. Any particular reason why you're explicitly choosing Python 3.8 here?

**Comment by AndreasAlbert** [comment]
No, tbh, I was just playing around trying to get it to work. (I did not know the python version from homebrew/ROOT)

**Comment by AndreasAlbert** [comment]
I'm confused actually that this now says that tests pass...When I last touched the code, I thought the tests were still failing? oO

**Comment by clelange** [comment]
We can stick to Python 3.8 or we go with the Homebrew default that we get with `root` (i.e not even install python explicitly with `brew`, but only `brew install root`). The latter might be easier. I'm actually a bit surprised this didn't cause issues.

**Comment by matthewfeickert** [comment]
@clelange I think this can get closed given the addition of 

https://github.com/HEPData/hepdata_lib/blob/21349a6f39726e7c7a1ddaa683a87f32e70ab79b/.github/workflows/tests.yml#L38-L41

in PR #220.

**Comment by clelange** [comment]
Superseded by #220

**Pull request closed without merging**
