### PR TITLE
build: Require Python 3.6+ for install

### LINKED ISSUE #219: Drop Python 2 support
Please drop support for Python 2. There are still components of `setup.py` and `setup.cfg` (also a lack of `python_requires`) that indicate that Python 2 is expected and supported

https://github.com/HEPData/hepdata_lib/blob/14fdd3e1d8ca9a9f4873ec903193c2970ee4bf26/setup.py#L41

https://github.com/HEPData/hepdata_lib/blob/14fdd3e1d8ca9a9f4873ec903193c2970ee4bf26/setup.cfg#L6

There is no reason for `hepdata_lib` to be used in the same environment that an LHC analysis needs to be run in, so there is no need to support environments that might be stuck in an environment that is Python 2 only.

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Resolves #219 
* Should follow PR #220.
* Requires PR #222 to go in first.

---

* Add requires-python metadata that requires Python 3.6+ for installation.
* Drop support for Python 2 by removing the universal information for wheels and qualifiers of Python version for pylint.
   - Remove setup.cfg as it was only holding universal wheel information and is currently not being used to hold any other configuration information
* Add Python 3.8, 3.9, 3.10 PyPI troves metadata.

----
:books: Documentation preview :books:: https://hepdata-lib--221.org.readthedocs.build/en/221/

### CODE REVIEW

**Comment by clelange** [comment]
https://pypi.org/project/hepdata-lib/0.11.1/ is up, so we can move ahead here. The metadata "requires" looks a bit odd on PyPI, but I guess this is OK?

```
Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.* 
```

**Comment by matthewfeickert** [comment]
To make things more atomic, I moved all the code cleaning and updating to PR #223, so this one _just_ updates the build dependencies and metadata to Python 3.6+.

**Comment by matthewfeickert** [comment]
> https://pypi.org/project/hepdata-lib/0.11.1/ is up, so we can move ahead here. The metadata "requires" looks a bit odd on PyPI, but I guess this is OK?
> 
> ```
> Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.* 
> ```

Yes, this is fine for Python 3.6+

```console
$ docker run --rm -ti python:3.6 /bin/bash
root@26b90d626fa6:/# python -m venv venv && . venv/bin/activate
(venv) root@26b90d626fa6:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@26b90d626fa6:/# python -m pip --quiet install hepdata-lib
(venv) root@26b90d626fa6:/# python -m pip show hepdata-lib
Name: hepdata-lib
Version: 0.11.1
Summary: Library for getting your data into HEPData
Home-page: https://github.com/HEPData/hepdata_lib
Author: Andreas Albert, Clemens Lange
Author-email: hepdata-lib@cern.ch
License: UNKNOWN
Location: /venv/lib/python3.6/site-packages
Requires: future, hepdata-validator, numpy, PyYAML, six
Required-by: 
(venv) root@26b90d626fa6:/# 
```

though c.f. Issue #224 for my recommendations on what to do once https://github.com/HEPData/hepdata_lib/pull/222#issuecomment-1441355145 is finished and there is a Python 3.6+ only release `v0.12.0` out.

**Comment by matthewfeickert** [comment]
@clelange this is ready for review now. Let me know if you have any questions.

**Review by clelange — APPROVED** [review]
I have no code comments, removal of `six` where it still exists and changing requirements to Python >= 3.6.

**Pull request merged**
