### PR TITLE
Implement one-sided uncertainty

### PR DESCRIPTION
**Pull request by AndreasAlbert**

### CODE REVIEW

**Comment by AndreasAlbert** [comment]
Closes #163

**Comment by AndreasAlbert** [comment]
Closes #154

**Comment by clelange** [comment]
I'm always a bit wary of this yaml representer thing, which seems to be working differently depending on the OS. I'll give this a try on macOS in the next few days (since we don't test that anymore in CI) and if that looks fine, I'll merge.

**Comment by clelange** [comment]
Nothing better than a CMS Physics Plenary to run some tests. They pass on macOS, merging :-)

**Review by clelange — APPROVED** [review]

**Pull request merged**
